# Generated by Django 5.2.10 on 2026-01-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_readme_file_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to image (use this for Vercel stability)'),
        ),
        migrations.AddField(
            model_name='project',
            name='readme_content',
            field=models.TextField(blank=True, help_text='Markdown content for the project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
