# Generated by Django 5.2.10 on 2026-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_image_url_project_readme_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='readme_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
