# Generated by Django 5.2.10 on 2026-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='readme_content',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='URL to project image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='readme_file',
            field=models.URLField(blank=True, help_text='URL to README file', max_length=500, null=True),
        ),
    ]
